### ISSUE TITLE
Wheel size

### ISSUE THREAD

**Issue by chrismonks** [starryalley/CSC_BLE_Bridge#16]
So now everything is workin, i'd like to change the wheel size to 700x28C

is it as simple as changing

**
    // 700x23c circumference in meter
    private static final BigDecimal circumference = new BigDecimal("2.095");**

to

**
    // 700x23c circumference in meter
    private static final BigDecimal circumference = new BigDecimal("2.136");**

AM i missing anything else, i suspect i am as I think BLE advertising also incorporates 700x23c profile, but not 100% on it. Any help greatly appreciated

**Comment by starryalley** [comment]
Hi @chrismonks,

I assume you are using ANT+ speed sensor with this app to ride in zwift?

When you set circumference in the code `private static final BigDecimal circumference = new BigDecimal("2.095");`, it only affects what is displayed on this app's screen. Bluetooth CSC profile (cycling speed and cadence) only specifies "Cumulative Wheel Revolutions". See [details here](https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Characteristics/org.bluetooth.characteristic.csc_measurement.xml). 

So that means whatever application is using that BLE CSC sensor advertised by this app should convert that revolution into meaningful speed figures. Zwift has wheel size setting when you try to connect with speed sensor (instead of power sensor). You have to set your wheel size there instead. 

Hope this clarifies.

**Comment by chrismonks** [comment]
Got ya.
Thanks for the very helpful answer. you guys are awesome.
My main issue was with zwift....I connected everything fine. The watts on my elite supercrono digital wireless was roughly 2X what zwift was show in their zpower calcs.
Did a bit of reading and played around with some of their trainer selected, was previously using "unknown" and boom, got a wattage on zwift within 2%+- what my trainer was telling me.

btw using an old timex speed/cadence/hr for ant+.

overall really great to be back on a bike after 8 year out......
