### ISSUE TITLE
Dependency not installed.

### ISSUE THREAD

**Issue by TyroneRoux** [starryalley/CSC_BLE_Bridge#21]
Help needed.
I am unable get get any sensors?  
I am using a Samsung Note 20 Ultra.
It keeps saying Dead (Dependency not installed)
What have I done wrong.

**Comment by starryalley** [comment]
Please search google play and install ANT Radio Service, ANT+ Plugins. 
FYI, S21 series and S20 FE have removed ANT+ support. Not sure about Note 20 ultra though.

**Comment by TyroneRoux** [comment]
![Screenshot_20210612-072415_Google Play Store](https://user-images.githubusercontent.com/85764333/121766063-b2598c00-cb4f-11eb-9fdc-1402a39adc86.jpg)

**Comment by TyroneRoux** [comment]
![Uploading Screenshot_20210611-210721_CSC BLE Bridge.jpg…]()

**Comment by starryalley** [comment]
I'm sorry @TyroneRoux I was not able to be helpful during last year about this issue. 

Now that there is another issue #23 where another user has encountered the same issue, and sent me a Android bug report, I realised that this could be due to Android 11's change that by default blocks this app's access to ANT+ services.

If possible can you check the apk I attached here and see if it fixes your issue?
https://github.com/starryalley/CSC_BLE_Bridge/issues/23#issuecomment-1016259422

Thank you.

**Comment by starryalley** [comment]
Release [v1.3.2](https://github.com/starryalley/CSC_BLE_Bridge/releases/tag/v1.3.2) should fix Android 11 ANT+ issues. If not, please re-open and let me know. Thank you.

**Comment by starryalley** [comment]
Closing this old issue.
